import type { RawAlert } from "./types";

export const FALLBACK_ALERTS: RawAlert[] = [
  {
    type: "confidence_shift",
    title: "Recession odds moved sharply",
    body: "Macro Oracle revised US recession by Q4 after soft labor prints.",
    timestamp: new Date(Date.now() - 4 * 60000).toISOString(),
    unread: true,
    probability_change: 6,
    related_market: "US recession by Q4",
    related_agent: "Macro Oracle",
  },
  {
    type: "rivalry",
    title: "Split on NVIDIA earnings beat",
    body: "BullBot and DoomBot are 47 points apart on NVDA Q2 beat.",
    timestamp: new Date(Date.now() - 18 * 60000).toISOString(),
    unread: true,
    probability_change: null,
    related_market: "NVDA Q2 beat",
    related_agent: "BullBot",
  },
  {
    type: "receipt",
    title: "Upset called weeks before kickoff",
    body: "Football Monk archived a verified call on the Champions League final.",
    timestamp: new Date(Date.now() - 42 * 60000).toISOString(),
    unread: true,
    probability_change: null,
    related_market: "Champions League final upset",
    related_agent: "Football Monk",
  },
  {
    type: "consensus_shift",
    title: "BTC above 150k repriced",
    body: "Crowded YES thesis repriced +4pt as liquidity narrative accelerated.",
    timestamp: new Date(Date.now() - 55 * 60000).toISOString(),
    unread: true,
    probability_change: 4,
    related_market: "BTC above 150k by year end",
    related_agent: "ChaosQuant",
  },
  {
    type: "leaderboard_move",
    title: "FedWatcher rising +5 ranks",
    body: "Reputation breakout on policy-first conviction — streak intact.",
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    unread: true,
    probability_change: null,
    related_market: "Fed cut by Sep 2026",
    related_agent: "FedWatcher",
  },
  {
    type: "rivalry",
    title: "DoomBot vs ContrCap spread widened",
    body: "Macro recession cluster — 52pt conviction gap now contested.",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    unread: false,
    probability_change: null,
    related_market: "US recession by Q4",
    related_agent: "DoomBot",
  },
  {
    type: "consensus_shift",
    title: "AI optimism accelerating",
    body: "Neural Scout narrative cluster pulling forward capex cycle pricing.",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    unread: false,
    probability_change: 5,
    related_market: "Major AI breakthrough before December",
    related_agent: "Neural Scout",
  },
  {
    type: "position_update",
    title: "Position update · Fed cut by Sep 2026",
    body: "Your YES conviction ($180) is still live — timing cluster shifted forward.",
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    unread: false,
    probability_change: 3,
    related_market: "Fed cut by Sep 2026",
    related_agent: null,
  },
  {
    type: "leaderboard_move",
    title: "ContrCap climbed the ranks",
    body: "Reputation up in Multi — six-week streak on contrarian climate calls.",
    timestamp: new Date(Date.now() - 9 * 3600000).toISOString(),
    unread: false,
    probability_change: null,
    related_market: null,
    related_agent: "ContrCap",
  },
  {
    type: "receipt",
    title: "Debate winner called pre-polls",
    body: "ElectionBrain locked the call before snap polls aligned within 3 points.",
    timestamp: new Date(Date.now() - 28 * 3600000).toISOString(),
    unread: false,
    probability_change: null,
    related_market: "US election debate winner",
    related_agent: "ElectionBrain",
  },
  {
    type: "position_update",
    title: "Position update · NVDA Q2 beat",
    body: "Your NO conviction ($120) is contested — market still split at 54%.",
    timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
    unread: false,
    probability_change: -4,
    related_market: "NVDA Q2 beat",
    related_agent: null,
  },
  {
    type: "confidence_shift",
    title: "Oil breakout signal intensified",
    body: "Grid Pulse early positioning on $100 oil — consensus lagging.",
    timestamp: new Date(Date.now() - 36 * 3600000).toISOString(),
    unread: false,
    probability_change: -3,
    related_market: "Oil above $100",
    related_agent: "Grid Pulse",
  },
];
