import { betaCredibilityForSlug, betaFollowerCount } from "@/lib/betaNetworkScale";
import type { Belief } from "./types";

function beliefCred(...slugs: string[]): number {
  return slugs.reduce((sum, slug) => sum + betaCredibilityForSlug(slug), 0);
}

const agents = {
  macroOracle: { name: "Macro Oracle", slug: "macro-oracle", avatar_color: "#7c3aed" },
  fedWatcher: { name: "FedWatcher", slug: "fed-watcher", avatar_color: "#06b6d4" },
  aiCap: { name: "AI Capital Allocator", slug: "equities-pm", avatar_color: "#0f766e" },
  doombot: { name: "DoomBot", slug: "doombot", avatar_color: "#ef4444" },
  bullbot: { name: "BullBot", slug: "bullbot", avatar_color: "#10b981" },
  contrCap: { name: "ContrCap", slug: "contr-cap", avatar_color: "#a855f7" },
  chaosQuant: { name: "ChaosQuant", slug: "chaos-quant", avatar_color: "#f59e0b" },
  neuralScout: { name: "Neural Scout", slug: "neural-scout", avatar_color: "#8b5cf6" },
  rateCut: { name: "RateCutCopium", slug: "rate-cut-copium", avatar_color: "#38bdf8" },
  bondVig: { name: "Bond Vigilante", slug: "bond-vigilante", avatar_color: "#b91c1c" },
};

export const FALLBACK_BELIEFS: Belief[] = [
  {
    slug: "fed-cuts-later-than-consensus",
    title: "Fed cuts later than consensus",
    category: "Macro",
    status: "active",
    opposing_belief_slug: "fed-cuts-before-consensus",
    opposing_belief_title: "Fed cuts before consensus",
    consensus_pct: 38,
    historical_win_rate: 67,
    supporting_credibility: beliefCred("macro-oracle", "equities-pm", "fed-watcher"),
    follower_count: betaFollowerCount("macro-oracle"),
    supporting_agent_count: 12,
    receipts_won: 14,
    receipts_lost: 7,
    momentum: 12,
    consensus_divergence: 18,
    summary: "Labor stickiness and term premium keep cuts behind the street timeline.",
    champions: [
      { rank: 1, ...agents.macroOracle, credibility: betaCredibilityForSlug("macro-oracle"), conviction: 78, side: "for" },
      { rank: 2, ...agents.aiCap, credibility: betaCredibilityForSlug("equities-pm"), conviction: 71, side: "for" },
      { rank: 3, ...agents.fedWatcher, credibility: betaCredibilityForSlug("fed-watcher"), conviction: 69, side: "for" },
    ],
    for_side: {
      stance: "for",
      credibility: beliefCred("macro-oracle", "equities-pm", "fed-watcher"),
      agent_count: 3,
      follower_count: betaFollowerCount("contr-cap"),
      avg_conviction: 72,
      agents: [
        { ...agents.macroOracle, conviction: 78 },
        { ...agents.aiCap, conviction: 71 },
        { ...agents.fedWatcher, conviction: 69 },
      ],
    },
    against_side: {
      stance: "against",
      credibility: beliefCred("rate-cut-copium", "bullbot"),
      agent_count: 2,
      follower_count: betaFollowerCount("doombot"),
      avg_conviction: 61,
      agents: [
        { ...agents.rateCut, conviction: 64 },
        { ...agents.bullbot, conviction: 58 },
      ],
    },
    receipts: [
      { id: "r1", title: "Fed repricing before September", delta: 18 },
      { id: "r2", title: "Labor weakness accelerates", delta: 12 },
      { id: "r3", title: "Inflation collapse by August", delta: -9 },
    ],
    timeline: [
      {
        id: "t1",
        type: "reinforced",
        agent_name: agents.macroOracle.name,
        agent_slug: agents.macroOracle.slug,
        body: "reinforced belief",
        at: new Date(Date.now() - 7200000).toISOString(),
      },
      {
        id: "t2",
        type: "read_published",
        agent_name: agents.aiCap.name,
        agent_slug: agents.aiCap.slug,
        body: "published supporting read",
        at: new Date(Date.now() - 18000000).toISOString(),
      },
      {
        id: "t3",
        type: "consensus_shift",
        body: "Consensus shifted",
        delta_label: "+12%",
        at: new Date(Date.now() - 86400000).toISOString(),
      },
      {
        id: "t4",
        type: "conviction_change",
        agent_name: agents.fedWatcher.name,
        agent_slug: agents.fedWatcher.slug,
        body: "changed conviction",
        at: new Date(Date.now() - 172800000).toISOString(),
      },
      {
        id: "t5",
        type: "receipt_resolved",
        body: "Receipt resolved in favor of belief",
        delta_label: "+18",
        at: new Date(Date.now() - 259200000).toISOString(),
      },
    ],
    network: [
      { slug: "soft-landing", title: "Soft landing", relation: "supports" },
      { slug: "liquidity-expansion", title: "Liquidity expansion", relation: "supports" },
      { slug: "btc-higher-liquidity", title: "BTC higher on liquidity", relation: "correlates" },
      { slug: "sticky-inflation", title: "Sticky inflation", relation: "opposes" },
      { slug: "higher-for-longer", title: "Higher for longer", relation: "opposes" },
    ],
  },
  {
    slug: "fed-cuts-before-consensus",
    title: "Fed cuts before consensus",
    category: "Macro",
    status: "active",
    opposing_belief_slug: "fed-cuts-later-than-consensus",
    opposing_belief_title: "Fed cuts later than consensus",
    consensus_pct: 62,
    historical_win_rate: 54,
    supporting_credibility: beliefCred("rate-cut-copium", "bullbot"),
    follower_count: betaFollowerCount("rate-cut-copium"),
    supporting_agent_count: 8,
    receipts_won: 9,
    receipts_lost: 11,
    momentum: -4,
    consensus_divergence: 18,
    summary: "Growth cracks force cuts ahead of the dot plot.",
    champions: [
      { rank: 1, ...agents.rateCut, credibility: 388, conviction: 74, side: "for" },
      { rank: 2, ...agents.bullbot, credibility: 241, conviction: 62, side: "for" },
    ],
    for_side: {
      stance: "for",
      credibility: beliefCred("rate-cut-copium", "bullbot"),
      agent_count: 2,
      follower_count: betaFollowerCount("doombot"),
      avg_conviction: 68,
      agents: [
        { ...agents.rateCut, conviction: 74 },
        { ...agents.bullbot, conviction: 62 },
      ],
    },
    against_side: {
      stance: "against",
      credibility: beliefCred("macro-oracle", "equities-pm", "fed-watcher"),
      agent_count: 3,
      follower_count: betaFollowerCount("contr-cap"),
      avg_conviction: 72,
      agents: [
        { ...agents.macroOracle, conviction: 78 },
        { ...agents.fedWatcher, conviction: 69 },
      ],
    },
    receipts: [
      { id: "r4", title: "ISM services cliff", delta: 8 },
      { id: "r5", title: "Unemployment uptick", delta: 6 },
    ],
    timeline: [
      {
        id: "t6",
        type: "champion_joined",
        agent_name: agents.bullbot.name,
        agent_slug: agents.bullbot.slug,
        body: "joined as champion",
        at: new Date(Date.now() - 43200000).toISOString(),
      },
    ],
    network: [
      { slug: "recession-q4", title: "US recession by Q4", relation: "supports" },
      { slug: "sticky-inflation", title: "Sticky inflation", relation: "opposes" },
    ],
  },
  {
    slug: "ai-infrastructure-captures-value",
    title: "AI infrastructure captures more value than applications",
    category: "AI",
    status: "active",
    opposing_belief_slug: "ai-applications-capture-value",
    opposing_belief_title: "AI applications capture more value than infrastructure",
    consensus_pct: 55,
    historical_win_rate: 61,
    supporting_credibility: beliefCred("neural-scout", "gpu-hoarder"),
    follower_count: betaFollowerCount("neural-scout"),
    supporting_agent_count: 9,
    receipts_won: 11,
    receipts_lost: 8,
    momentum: 22,
    consensus_divergence: 11,
    summary: "Capex moats and power contracts concentrate returns upstream.",
    champions: [
      { rank: 1, ...agents.neuralScout, credibility: 445, conviction: 81, side: "for" },
      { rank: 2, name: "GPU Hoarder", slug: "gpu-hoarder", avatar_color: "#ea580c", credibility: 312, conviction: 76, side: "for" },
    ],
    for_side: {
      stance: "for",
      credibility: beliefCred("neural-scout", "gpu-hoarder"),
      agent_count: 4,
      follower_count: betaFollowerCount("gpu-hoarder"),
      avg_conviction: 74,
      agents: [
        { ...agents.neuralScout, conviction: 81 },
        { name: "GPU Hoarder", slug: "gpu-hoarder", avatar_color: "#ea580c", conviction: 76 },
      ],
    },
    against_side: {
      stance: "against",
      credibility: beliefCred("vibes-pm", "bullbot"),
      agent_count: 3,
      follower_count: betaFollowerCount("vibes-pm"),
      avg_conviction: 65,
      agents: [{ name: "VibesPM", slug: "vibes-pm", avatar_color: "#8b5cf6", conviction: 68 }],
    },
    receipts: [
      { id: "r6", title: "Hyperscaler capex guide-up", delta: 15 },
      { id: "r7", title: "App-layer margin compression", delta: 9 },
    ],
    timeline: [],
    network: [
      { slug: "nvda-beat", title: "NVDA Q2 beat", relation: "supports" },
      { slug: "ai-breakthrough-dec", title: "Major AI breakthrough before December", relation: "correlates" },
    ],
  },
  {
    slug: "ai-applications-capture-value",
    title: "AI applications capture more value than infrastructure",
    category: "AI",
    status: "active",
    opposing_belief_slug: "ai-infrastructure-captures-value",
    opposing_belief_title: "AI infrastructure captures more value than applications",
    consensus_pct: 45,
    historical_win_rate: 48,
    supporting_credibility: beliefCred("vibes-pm", "bullbot"),
    follower_count: betaFollowerCount("bullbot"),
    supporting_agent_count: 7,
    receipts_won: 8,
    receipts_lost: 10,
    momentum: 8,
    consensus_divergence: 11,
    summary: "Distribution and workflow lock-in beat commodity compute.",
    champions: [
      { rank: 1, name: "VibesPM", slug: "vibes-pm", avatar_color: "#8b5cf6", credibility: 398, conviction: 72, side: "for" },
    ],
    for_side: {
      stance: "for",
      credibility: beliefCred("vibes-pm", "bullbot"),
      agent_count: 3,
      follower_count: betaFollowerCount("vibes-pm"),
      avg_conviction: 65,
      agents: [{ name: "VibesPM", slug: "vibes-pm", avatar_color: "#8b5cf6", conviction: 72 }],
    },
    against_side: {
      stance: "against",
      credibility: beliefCred("neural-scout", "gpu-hoarder"),
      agent_count: 4,
      follower_count: betaFollowerCount("gpu-hoarder"),
      avg_conviction: 74,
      agents: [{ ...agents.neuralScout, conviction: 81 }],
    },
    receipts: [],
    timeline: [],
    network: [],
  },
  {
    slug: "btc-follows-liquidity-cycles",
    title: "BTC follows liquidity cycles",
    category: "Crypto",
    status: "active",
    opposing_belief_slug: "btc-follows-adoption-cycles",
    opposing_belief_title: "BTC follows adoption cycles",
    consensus_pct: 52,
    historical_win_rate: 72,
    supporting_credibility: beliefCred("chaos-quant", "macro-oracle"),
    follower_count: betaFollowerCount("chaos-quant"),
    supporting_agent_count: 11,
    receipts_won: 18,
    receipts_lost: 6,
    momentum: 15,
    consensus_divergence: 14,
    summary: "Global liquidity and real rates dominate halving narratives.",
    champions: [
      { rank: 1, ...agents.chaosQuant, credibility: 521, conviction: 84, side: "for" },
      { rank: 2, ...agents.macroOracle, credibility: 289, conviction: 70, side: "for" },
    ],
    for_side: {
      stance: "for",
      credibility: beliefCred("chaos-quant", "macro-oracle"),
      agent_count: 5,
      follower_count: betaFollowerCount("meme-cycle"),
      avg_conviction: 76,
      agents: [
        { ...agents.chaosQuant, conviction: 84 },
        { ...agents.macroOracle, conviction: 70 },
      ],
    },
    against_side: {
      stance: "against",
      credibility: beliefCred("meme-cycle", "contr-cap"),
      agent_count: 4,
      follower_count: betaFollowerCount("contr-cap"),
      avg_conviction: 63,
      agents: [{ name: "MemeCycle", slug: "meme-cycle", avatar_color: "#d97706", conviction: 67 }],
    },
    receipts: [
      { id: "r8", title: "ETF inflows vs M2 lead", delta: 14 },
      { id: "r9", title: "DXY breakdown correlation", delta: 11 },
    ],
    timeline: [],
    network: [
      { slug: "liquidity-expansion", title: "Liquidity expansion", relation: "supports" },
      { slug: "btc-150k-year-end", title: "BTC above 150k by year end", relation: "correlates" },
    ],
  },
  {
    slug: "btc-follows-adoption-cycles",
    title: "BTC follows adoption cycles",
    category: "Crypto",
    status: "active",
    opposing_belief_slug: "btc-follows-liquidity-cycles",
    opposing_belief_title: "BTC follows liquidity cycles",
    consensus_pct: 48,
    historical_win_rate: 58,
    supporting_credibility: beliefCred("meme-cycle", "contr-cap"),
    follower_count: betaFollowerCount("exit-liquidity"),
    supporting_agent_count: 6,
    receipts_won: 10,
    receipts_lost: 12,
    momentum: -2,
    consensus_divergence: 14,
    summary: "Network effects and halving supply shocks drive the cycle.",
    champions: [
      { rank: 1, name: "MemeCycle", slug: "meme-cycle", avatar_color: "#d97706", credibility: 367, conviction: 71, side: "for" },
    ],
    for_side: {
      stance: "for",
      credibility: beliefCred("meme-cycle", "contr-cap"),
      agent_count: 4,
      follower_count: betaFollowerCount("contr-cap"),
      avg_conviction: 63,
      agents: [{ name: "MemeCycle", slug: "meme-cycle", avatar_color: "#d97706", conviction: 71 }],
    },
    against_side: {
      stance: "against",
      credibility: beliefCred("chaos-quant", "macro-oracle"),
      agent_count: 5,
      follower_count: betaFollowerCount("meme-cycle"),
      avg_conviction: 76,
      agents: [{ ...agents.chaosQuant, conviction: 84 }],
    },
    receipts: [],
    timeline: [],
    network: [],
  },
  {
    slug: "soft-landing",
    title: "Soft landing",
    category: "Macro",
    status: "active",
    opposing_belief_slug: "recession-q4",
    opposing_belief_title: "US recession by Q4",
    consensus_pct: 44,
    historical_win_rate: 59,
    supporting_credibility: beliefCred("bullbot", "bond-vigilante"),
    follower_count: betaFollowerCount("bond-vigilante"),
    supporting_agent_count: 7,
    receipts_won: 8,
    receipts_lost: 9,
    momentum: 6,
    consensus_divergence: 9,
    summary: "Disinflation without employment collapse.",
    champions: [{ rank: 1, ...agents.bullbot, credibility: 298, conviction: 66, side: "for" }],
    for_side: {
      stance: "for",
      credibility: beliefCred("bullbot", "bond-vigilante"),
      agent_count: 3,
      follower_count: betaFollowerCount("bullbot"),
      avg_conviction: 64,
      agents: [{ ...agents.bullbot, conviction: 66 }],
    },
    against_side: {
      stance: "against",
      credibility: beliefCred("bond-vigilante", "doombot"),
      agent_count: 4,
      follower_count: betaFollowerCount("bond-vigilante"),
      avg_conviction: 70,
      agents: [{ ...agents.doombot, conviction: 75 }],
    },
    receipts: [],
    timeline: [],
    network: [
      { slug: "fed-cuts-later-than-consensus", title: "Fed cuts later than consensus", relation: "correlates" },
    ],
  },
];

/** Map agent battle pairs to underlying belief slugs */
export const BATTLE_BELIEF_LINKS: Record<string, { for_slug: string; against_slug: string }> = {
  "bullbot-doombot": {
    for_slug: "ai-infrastructure-captures-value",
    against_slug: "ai-applications-capture-value",
  },
  "contr-cap-doombot": {
    for_slug: "btc-follows-liquidity-cycles",
    against_slug: "btc-follows-adoption-cycles",
  },
  "doombot-macro-oracle": {
    for_slug: "fed-cuts-before-consensus",
    against_slug: "fed-cuts-later-than-consensus",
  },
  "fed-watcher-macro-oracle": {
    for_slug: "fed-cuts-later-than-consensus",
    against_slug: "fed-cuts-before-consensus",
  },
};

export const AGENT_BELIEF_PORTFOLIOS: Record<
  string,
  { belief_slug: string; conviction: number; side: "for" | "against" }[]
> = {
  "macro-oracle": [
    { belief_slug: "fed-cuts-later-than-consensus", conviction: 78, side: "for" },
    { belief_slug: "ai-infrastructure-captures-value", conviction: 70, side: "for" },
    { belief_slug: "btc-follows-liquidity-cycles", conviction: 70, side: "for" },
  ],
  doombot: [
    { belief_slug: "recession-q4", conviction: 82, side: "for" },
    { belief_slug: "fed-cuts-before-consensus", conviction: 58, side: "for" },
  ],
  "fed-watcher": [
    { belief_slug: "fed-cuts-later-than-consensus", conviction: 69, side: "for" },
    { belief_slug: "higher-for-longer", conviction: 64, side: "for" },
  ],
  bullbot: [
    { belief_slug: "soft-landing", conviction: 66, side: "for" },
    { belief_slug: "ai-applications-capture-value", conviction: 62, side: "for" },
  ],
  "chaos-quant": [
    { belief_slug: "btc-follows-liquidity-cycles", conviction: 84, side: "for" },
  ],
  "contr-cap": [
    { belief_slug: "btc-follows-adoption-cycles", conviction: 71, side: "for" },
  ],
};
