import type { NarrativesPayload } from "./types";

export const FALLBACK_NARRATIVES: NarrativesPayload = {
  trending_narratives: [
    {
      title: "AI optimism accelerating",
      description:
        "Tech conviction clustering higher as agents stack high-confidence YES takes on breakthrough timelines.",
      type: "momentum_up",
      direction: "up",
      strength: 84.2,
      change: 11.3,
      agents_involved: ["bullbot", "contr-cap", "neural-scout"],
      markets_involved: ["Major AI breakthrough before December"],
      created_at: new Date().toISOString(),
    },
    {
      title: "Soft landing weakening",
      description:
        "Macro agents repricing recession timing while Fed-cut consensus pulls forward — alignment fracturing on growth.",
      type: "consensus_shift",
      direction: "down",
      strength: 76.5,
      change: 9.2,
      agents_involved: ["fed-watcher", "macro-oracle", "doombot"],
      markets_involved: ["US recession by Q4", "Fed cut by Sep 2026"],
      created_at: new Date().toISOString(),
    },
    {
      title: "ETF demand supercycle",
      description:
        "Equities narrative converging on liquidity inflows — conviction clustering across tech and macro crossover markets.",
      type: "narrative_breakout",
      direction: "up",
      strength: 72.1,
      change: 8.7,
      agents_involved: ["bullbot", "chaos-quant"],
      markets_involved: ["NVDA Q2 beat"],
      created_at: new Date().toISOString(),
    },
    {
      title: "Crypto liquidity repricing",
      description:
        "Year-end targets contested while spreads refuse to converge — memetic repricing across crypto agents.",
      type: "disagreement",
      direction: "split",
      strength: 71.8,
      change: 8.4,
      agents_involved: ["chaos-quant", "contr-cap"],
      markets_involved: ["BTC above 150k by year end"],
      created_at: new Date().toISOString(),
    },
    {
      title: "Election volatility rising",
      description:
        "Politics cluster front-running polling cycles — probability bands widening pre-consensus lock.",
      type: "narrative_breakout",
      direction: "up",
      strength: 68.4,
      change: 7.6,
      agents_involved: ["election-brain", "policy-pulse"],
      markets_involved: ["US election debate winner", "PA incumbent wins"],
      created_at: new Date().toISOString(),
    },
    {
      title: "Climate regulation repricing",
      description:
        "Policy agents building streaks on carbon transition — emerging consensus toward YES on EU policy shift.",
      type: "momentum_up",
      direction: "up",
      strength: 64.2,
      change: 5.8,
      agents_involved: ["climate-scout", "contr-cap"],
      markets_involved: ["EU carbon policy shift"],
      created_at: new Date().toISOString(),
    },
  ],
  consensus_shifts: [
    {
      title: "Fed cut timing pulled forward",
      description: "Multiple agents now cluster on September vs. December — consensus convergence accelerating.",
      type: "consensus_shift",
      direction: "up",
      strength: 68.0,
      change: 7.0,
      agents_involved: ["fed-watcher", "macro-oracle"],
      markets_involved: ["Fed cut by Sep 2026"],
      created_at: new Date().toISOString(),
    },
    {
      title: "Energy shock narrative cooling",
      description: "Commodity conviction decelerating as supply narratives lose agent alignment.",
      type: "momentum_down",
      direction: "down",
      strength: 58.3,
      change: 6.2,
      agents_involved: ["grid-pulse"],
      markets_involved: ["Oil above $100"],
      created_at: new Date().toISOString(),
    },
  ],
  expanding_disagreements: [
    {
      title: "Sports upset momentum",
      description: "Contrarian agents stacking upset takes — alignment low but velocity rising on finals markets.",
      type: "disagreement",
      direction: "split",
      strength: 62.5,
      change: 7.8,
      agents_involved: ["football-monk", "chaos-quant"],
      markets_involved: ["Champions League final upset", "Premier League title race"],
      created_at: new Date().toISOString(),
    },
    {
      title: "Split forming on NVDA Q2 beat",
      description: "BullBot at 78% YES vs DoomBot at 31% NO — conviction fracture widening.",
      type: "disagreement",
      direction: "split",
      strength: 82.1,
      change: 9.5,
      agents_involved: ["bullbot", "doombot"],
      markets_involved: ["NVDA Q2 beat"],
      created_at: new Date().toISOString(),
    },
  ],
  momentum_markets: [
    {
      category: "AI",
      direction: "up",
      strength: 78,
      change: 9.2,
      agent_count: 14,
      markets_involved: ["Major AI breakthrough before December"],
    },
    {
      category: "Macro",
      direction: "down",
      strength: 65,
      change: 7.1,
      agent_count: 22,
      markets_involved: ["US recession by Q4", "Fed cut by Sep 2026"],
    },
    {
      category: "Crypto",
      direction: "split",
      strength: 71,
      change: 8.4,
      agent_count: 11,
      markets_involved: ["BTC above 150k by year end"],
    },
    {
      category: "Sports",
      direction: "up",
      strength: 48,
      change: 4.2,
      agent_count: 8,
      markets_involved: ["Champions League final upset"],
    },
    {
      category: "Politics",
      direction: "up",
      strength: 58,
      change: 6.1,
      agent_count: 9,
      markets_involved: ["US election debate winner"],
    },
    {
      category: "Climate",
      direction: "up",
      strength: 62,
      change: 5.8,
      agent_count: 7,
      markets_involved: ["EU carbon policy shift"],
    },
  ],
};
