import type { ScryReceipt } from "./types";

/** Demo resolved calls — swap for API when backend is ready. */
export const DEMO_SCRY_RECEIPTS: ScryReceipt[] = [
  {
    id: "receipt-fed-repricing",
    forecastTitle: "Fed cut narrative repricing before September",
    calledProbability: 72,
    consensusAtCall: 41,
    side: "YES",
    calledAt: "2026-05-12",
    resolvedAt: "2026-05-26",
    outcome: "correct",
    credibilityDelta: 18,
    reasoningExcerpt: "Market was underpricing labor softness and Fed language shift.",
    receiptStatus: "verified",
  },
  {
    id: "receipt-oil-reversal",
    forecastTitle: "Oil reversal after OPEC surprise hold",
    calledProbability: 64,
    consensusAtCall: 52,
    side: "NO",
    calledAt: "2026-05-08",
    resolvedAt: "2026-05-20",
    outcome: "correct",
    credibilityDelta: 14,
    reasoningExcerpt: "Inventory builds and demand revision cycle pointed to fade.",
    receiptStatus: "verified",
  },
  {
    id: "receipt-recession-risk",
    forecastTitle: "Recession risk repricing in H2 guidance",
    calledProbability: 58,
    consensusAtCall: 34,
    side: "YES",
    calledAt: "2026-04-28",
    resolvedAt: "2026-05-15",
    outcome: "correct",
    credibilityDelta: 22,
    reasoningExcerpt: "Credit spreads and payroll revisions broke consensus complacency.",
    receiptStatus: "verified",
  },
  {
    id: "receipt-fed-consensus-break",
    forecastTitle: "Fed cut consensus break before June meeting",
    calledProbability: 61,
    consensusAtCall: 38,
    side: "YES",
    calledAt: "2026-04-18",
    resolvedAt: "2026-05-02",
    outcome: "correct",
    credibilityDelta: 9,
    reasoningExcerpt: "Dot plot drift and swap pricing diverged from headline consensus.",
    receiptStatus: "verified",
  },
  {
    id: "receipt-btc-breakout",
    forecastTitle: "BTC above 150k by June",
    calledProbability: 81,
    consensusAtCall: 54,
    side: "YES",
    calledAt: "2026-03-22",
    resolvedAt: "2026-05-10",
    outcome: "missed",
    credibilityDelta: -9,
    reasoningExcerpt: "Liquidity impulse looked stronger than on-chain distribution suggested.",
    receiptStatus: "verified",
  },
  {
    id: "receipt-ai-infra",
    forecastTitle: "AI infrastructure capex overcall into Q2",
    calledProbability: 76,
    consensusAtCall: 61,
    side: "YES",
    calledAt: "2026-03-10",
    resolvedAt: "2026-04-28",
    outcome: "missed",
    credibilityDelta: -4,
    reasoningExcerpt: "Hyperscaler guidance already priced extension risk.",
    receiptStatus: "verified",
  },
  {
    id: "receipt-euro-cpi",
    forecastTitle: "Eurozone CPI stickiness surprise in April",
    calledProbability: 55,
    consensusAtCall: 48,
    side: "YES",
    calledAt: "2026-05-18",
    resolvedAt: null,
    outcome: "pending",
    credibilityDelta: 0,
    reasoningExcerpt: "Services inflation persistence vs energy base effects.",
    receiptStatus: "pending",
  },
  {
    id: "receipt-yen-intervention",
    forecastTitle: "BOJ intervention window before 160 USD/JPY",
    calledProbability: 49,
    consensusAtCall: 31,
    side: "YES",
    calledAt: "2026-05-22",
    resolvedAt: null,
    outcome: "pending",
    credibilityDelta: 0,
    reasoningExcerpt: "Ministry rhetoric and options skew implied asymmetric risk.",
    receiptStatus: "pending",
  },
];
