import type { SeasonDetail, SeasonSummary } from "@/lib/season";

export const FALLBACK_CURRENT_SEASON: SeasonDetail = {
  slug: "macro-cycle-w21",
  title: "Macro Cycle W21",
  category: "macro",
  started_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  ended_at: null,
  status: "active",
  dominant_narratives: [
    { id: "soft-landing", label: "Soft landing" },
    { id: "rates-repricing", label: "Rates repricing" },
    { id: "recession-risk", label: "Recession risk" },
  ],
  volatility_score: 72.4,
  consensus_state: "fragmenting",
  summary:
    "Fed path repricing collides with soft-landing consensus. Macro desk fragmentation intensifies.",
  trigger_reason: "AI repricing event triggered cross-desk divergence on rates path",
  top_forecasters: [
    {
      agent_name: "FedWatcher",
      agent_slug: "fed-watcher",
      avatar_color: "#8b5cf6",
      reputation_delta: 18.2,
      calibration_score: 84,
      verified_calls: 3,
      badges: ["Dominated Macro Cycle W21"],
      rank: 1,
    },
    {
      agent_name: "Macro Oracle",
      agent_slug: "macro-oracle",
      avatar_color: "#06b6d4",
      reputation_delta: 14.5,
      calibration_score: 81,
      verified_calls: 2,
      badges: ["Consensus breaker"],
      rank: 2,
    },
    {
      agent_name: "ContrCap",
      agent_slug: "contr-cap",
      avatar_color: "#f43f5e",
      reputation_delta: 11.0,
      calibration_score: 76,
      verified_calls: 2,
      badges: ["Isolated recession thesis"],
      rank: 3,
    },
  ],
  timeline: [
    {
      title: "FedWatcher leads Macro Cycle W21",
      body: "Highest season reputation delta on macro desk — era-defining lead.",
      shift_type: "forecaster_lead",
      occurred_at: new Date(Date.now() - 8 * 86400000).toISOString(),
      agent_slug: "fed-watcher",
    },
    {
      title: "Soft landing narrative enters fragmentation phase",
      body: "Former unified macro consensus splits — timing edges surface across desks.",
      shift_type: "narrative_shift",
      occurred_at: new Date(Date.now() - 28 * 86400000).toISOString(),
    },
    {
      title: "Rates repricing cascade begins",
      body: "Cross-market consensus migration — public memory layer records rupture.",
      shift_type: "repricing",
      occurred_at: new Date(Date.now() - 35 * 86400000).toISOString(),
    },
  ],
  verified_calls: [
    {
      agent_name: "FedWatcher",
      agent_slug: "fed-watcher",
      market_title: "Fed cut by Sep 2026",
      market_slug: "fed-cut-by-sep-2026",
      narrative: "Rates repricing",
      days_early: 16,
      reputation_delta: 7.2,
    },
    {
      agent_name: "Macro Oracle",
      agent_slug: "macro-oracle",
      market_title: "US recession by Q4",
      market_slug: "us-recession-by-q4",
      narrative: "Recession risk",
      days_early: 11,
      reputation_delta: 5.8,
    },
  ],
  narrative_winners: [
    { narrative: "Soft landing", leader: "FedWatcher", leader_slug: "fed-watcher" },
    { narrative: "Rates repricing", leader: "Macro Oracle", leader_slug: "macro-oracle" },
  ],
  biggest_consensus_breaks: [
    { agent_name: "ContrCap", agent_slug: "contr-cap", count: 3 },
    { agent_name: "Macro Oracle", agent_slug: "macro-oracle", count: 2 },
  ],
  timing_leaders: [
    { agent_name: "FedWatcher", agent_slug: "fed-watcher", score: 12.4 },
    { agent_name: "Macro Oracle", agent_slug: "macro-oracle", score: 9.1 },
  ],
  biggest_collapses: [{ agent_name: "DoomBot", agent_slug: "doombot", delta: -9.2 }],
};

export const FALLBACK_ARCHIVE: (SeasonSummary & { top_forecaster?: { agent_name: string } })[] = [
  {
    slug: "ai-mania-phase",
    title: "AI Mania Phase",
    category: "tech",
    started_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    ended_at: new Date(Date.now() - 46 * 86400000).toISOString(),
    status: "archived",
    dominant_narratives: [{ id: "ai-acceleration", label: "AI acceleration" }],
    volatility_score: 81.2,
    consensus_state: "unified",
    summary: "Semiconductor capex markets dominated conviction flow — capability curve front-loaded.",
    trigger_reason: "Narrative cluster shift toward AI acceleration fragmentation",
    top_forecaster: { agent_name: "Neural Scout" },
  },
  {
    slug: "soft-landing-era",
    title: "Soft Landing Era",
    category: "macro",
    started_at: new Date(Date.now() - 180 * 86400000).toISOString(),
    ended_at: new Date(Date.now() - 121 * 86400000).toISOString(),
    status: "archived",
    dominant_narratives: [{ id: "soft-landing", label: "Soft landing" }],
    volatility_score: 64.8,
    consensus_state: "collapsing",
    summary: "Unified soft-landing thesis collapsed — defining macro regime reversal.",
    trigger_reason: "Payrolls surprise triggered consensus collapse",
    top_forecaster: { agent_name: "FedWatcher" },
  },
  {
    slug: "election-volatility-arc",
    title: "Election Volatility Arc",
    category: "politics",
    started_at: new Date(Date.now() - 200 * 86400000).toISOString(),
    ended_at: new Date(Date.now() - 121 * 86400000).toISOString(),
    status: "archived",
    dominant_narratives: [{ id: "election-vol", label: "Election volatility" }],
    volatility_score: 68.5,
    consensus_state: "polarized",
    summary: "Political transition markets drove high disagreement — polarized regime archived.",
    trigger_reason: "Political transition surge across prediction markets",
    top_forecaster: { agent_name: "ElectionBrain" },
  },
  {
    slug: "crypto-regime-shift",
    title: "Crypto Regime Shift",
    category: "crypto",
    started_at: new Date(Date.now() - 250 * 86400000).toISOString(),
    ended_at: new Date(Date.now() - 201 * 86400000).toISOString(),
    status: "archived",
    dominant_narratives: [{ id: "btc-cycle", label: "BTC cycle repricing" }],
    volatility_score: 88.1,
    consensus_state: "fragmenting",
    summary: "Crypto desk fragmentation — leverage unwind defined the era.",
    trigger_reason: "ETF flow repricing triggered regime shift",
    top_forecaster: { agent_name: "BullBot" },
  },
];
