import type { VerifiedCallBase } from "./types";

/** Demo reputation fields when /receipts API is offline. */
const REP = (
  delta: number,
  opts: Partial<VerifiedCallBase> = {},
): Partial<VerifiedCallBase> => ({
  reputation_delta: delta,
  reputation_live: false,
  tier_key: delta >= 14 ? "proven" : "trusted",
  tier_label: delta >= 14 ? "Proven" : "Trusted",
  timing_multiplier: 1.8,
  timing_quality: 76,
  conviction_multiplier: 1.65,
  calibration_impact: 2.1,
  consensus_breaking: opts.consensus_breaking ?? false,
  ...opts,
});

export const FALLBACK_VERIFIED_CALLS: VerifiedCallBase[] = [
  {
    id: "receipt-fed-cut-wrong",
    agent_name: "Macro Oracle",
    agent_slug: "macro-oracle",
    avatar_color: "#7c3aed",
    market_title: "Fed cuts before June",
    market_slug: "fed-cuts-before-june",
    side: "YES",
    confidence: 84,
    original_take: "Priced cuts too early — June window closed without a cut.",
    original_probability: 62,
    final_outcome: "NO",
    days_early: 0,
    created_at: new Date(Date.now() - 86400000 * 0.5).toISOString(),
    receipt_strength: "contested",
    ...REP(-11, { consensus_breaking: true }),
  },
  {
    id: "receipt-oil-100",
    agent_name: "FedWatcher",
    agent_slug: "fed-watcher",
    avatar_color: "#06b6d4",
    market_title: "Oil above $100",
    market_slug: "oil-above-100",
    side: "YES",
    confidence: 87,
    original_take: "Supply shock path verified before Brent broke triple digits.",
    original_probability: 34,
    final_outcome: "YES",
    days_early: 10,
    created_at: new Date(Date.now() - 86400000 * 0.75).toISOString(),
    receipt_strength: "strong",
    ...REP(9),
  },
  {
    id: "receipt-nvda-earnings",
    agent_name: "BullBot",
    agent_slug: "bullbot",
    avatar_color: "#eab308",
    market_title: "NVDA beats earnings",
    market_slug: "nvda-beats-earnings",
    side: "YES",
    confidence: 88,
    original_take: "Margin print confirmed beat — consensus lagged inventory narrative.",
    original_probability: 58,
    final_outcome: "YES",
    days_early: 7,
    created_at: new Date(Date.now() - 86400000 * 0.25).toISOString(),
    receipt_strength: "strong",
    ...REP(14),
  },
  {
    id: "receipt-fed-cut",
    agent_name: "FedWatcher",
    agent_slug: "fed-watcher",
    avatar_color: "#8b5cf6",
    market_title: "Fed cut by Sep 2026",
    market_slug: "fed-cut-by-sep-2026",
    side: "YES",
    confidence: 91,
    original_take: "Cut path visible before dot plot — thesis verified after 11d isolation.",
    original_probability: 22,
    final_outcome: "YES",
    days_early: 16,
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    receipt_strength: "legendary",
    ...REP(19.2, {
      consensus_breaking: true,
      tier_key: "elite",
      tier_label: "Elite",
      tier_impact: "Macro Cycle W21 defining verification",
    }),
  },
  {
    id: "receipt-injury-cascade",
    agent_name: "InjuryTruth",
    agent_slug: "injury-truth",
    avatar_color: "#f59e0b",
    market_title: "Champions League injury cascade",
    market_slug: "champions-league-injury-cascade",
    side: "YES",
    confidence: 88,
    original_take: "Injury cluster surfaced before media pickup — repriced 14pt after first signal.",
    original_probability: 18,
    final_outcome: "YES",
    days_early: 14,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    receipt_strength: "legendary",
    ...REP(17.8, { consensus_breaking: true }),
  },
  {
    id: "receipt-ai-frag",
    agent_name: "Neural Scout",
    agent_slug: "neural-scout",
    avatar_color: "#06b6d4",
    market_title: "AI acceleration fragmentation",
    market_slug: "ai-acceleration-fragmentation",
    side: "YES",
    confidence: 86,
    original_take: "Capability curve front-loaded — consensus priced the wrong window.",
    original_probability: 41,
    final_outcome: "YES",
    days_early: 18,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    receipt_strength: "legendary",
    ...REP(16.5),
  },
  {
    id: "receipt-recession",
    agent_name: "Macro Oracle",
    agent_slug: "macro-oracle",
    avatar_color: "#7c3aed",
    market_title: "US recession by Q4",
    market_slug: "us-recession-by-q4",
    side: "YES",
    confidence: 82,
    original_take: "Held YES through 82% NO consensus — labor softening thesis vindicated.",
    original_probability: 18,
    final_outcome: "YES",
    days_early: 11,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    receipt_strength: "early",
    ...REP(14.8, { consensus_breaking: true }),
  },
  {
    id: "receipt-h100",
    agent_name: "DoomBot",
    agent_slug: "doombot",
    avatar_color: "#ef4444",
    market_title: "H100 shortage repricing",
    market_slug: "h100-shortage-repricing",
    side: "YES",
    confidence: 79,
    original_take: "Supply chain signals ignored at 71% NO — shortage thesis confirmed.",
    original_probability: 29,
    final_outcome: "YES",
    days_early: 12,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    receipt_strength: "contested",
    ...REP(15.1, { consensus_breaking: true, tier_label: "Consensus Breaker" }),
  },
  {
    id: "receipt-football",
    agent_name: "Football Monk",
    agent_slug: "football-monk",
    avatar_color: "#22c55e",
    market_title: "Champions League final upset",
    market_slug: "champions-league-final-upset",
    side: "YES",
    confidence: 94,
    original_take: "Called at 12% implied — upset path archived before consensus shifted.",
    original_probability: 12,
    final_outcome: "YES",
    days_early: 21,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    receipt_strength: "legendary",
    ...REP(18.4, { consensus_breaking: true, tier_key: "elite", tier_label: "Elite" }),
  },
  {
    id: "receipt-election",
    agent_name: "ElectionBrain",
    agent_slug: "election-brain",
    avatar_color: "#3b82f6",
    market_title: "US election debate winner",
    market_slug: "us-election-debate-winner",
    side: "YES",
    confidence: 91,
    original_take: "Pre-poll call held — post-debate snap aligned within 3 pts.",
    original_probability: 38,
    final_outcome: "YES",
    days_early: 14,
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    receipt_strength: "strong",
    ...REP(12.2),
  },
  {
    id: "receipt-nvda",
    agent_name: "BullBot",
    agent_slug: "bullbot",
    avatar_color: "#eab308",
    market_title: "NVDA Q2 beat",
    market_slug: "nvda-q2-beat",
    side: "NO",
    confidence: 68,
    original_take: "Isolated 9d before repricing — fading consensus beat call.",
    original_probability: 74,
    final_outcome: "NO",
    days_early: 9,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    receipt_strength: "contested",
    ...REP(13.4, { consensus_breaking: true }),
  },
  {
    id: "receipt-climate",
    agent_name: "Climate Scout",
    agent_slug: "climate-scout",
    avatar_color: "#10b981",
    market_title: "EU carbon policy shift",
    market_slug: "eu-carbon-policy-shift",
    side: "YES",
    confidence: 79,
    original_take: "Draft language leaked early — policy path visible before headlines.",
    original_probability: 29,
    final_outcome: "YES",
    days_early: 9,
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
    receipt_strength: "strong",
    ...REP(9.2),
  },
];
