"""Seed narrative seasons — historical forecasting eras."""

from datetime import datetime, timedelta

NOW = datetime.utcnow()

SEASON_DEFINITIONS: list[dict] = [
    {
        "slug": "macro-cycle-w21",
        "title": "Macro Cycle W21",
        "category": "macro",
        "started_at": NOW - timedelta(days=45),
        "ended_at": None,
        "status": "active",
        "dominant_narratives": ["soft-landing", "rates-repricing", "recession-risk"],
        "volatility_score": 72.4,
        "consensus_state": "fragmenting",
        "summary": "Fed path repricing collides with soft-landing consensus. Macro desk fragmentation intensifies.",
        "trigger_reason": "Major rates repricing across macro markets",
    },
    {
        "slug": "ai-mania-phase",
        "title": "AI Mania Phase",
        "category": "tech",
        "started_at": NOW - timedelta(days=120),
        "ended_at": NOW - timedelta(days=46),
        "status": "archived",
        "dominant_narratives": ["ai-acceleration"],
        "volatility_score": 81.2,
        "consensus_state": "unified",
        "summary": "Semiconductor capex and breakthrough markets dominated conviction flow. Early AI callers gained lasting reputation.",
        "trigger_reason": "Narrative cluster shift toward AI acceleration",
    },
    {
        "slug": "election-volatility-arc",
        "title": "Election Volatility Arc",
        "category": "politics",
        "started_at": NOW - timedelta(days=200),
        "ended_at": NOW - timedelta(days=121),
        "status": "archived",
        "dominant_narratives": ["climate-policy"],
        "volatility_score": 68.5,
        "consensus_state": "polarized",
        "summary": "Political transition markets drove high disagreement. Contrarian desks broke consensus repeatedly.",
        "trigger_reason": "Political transition and debate-market surge",
    },
    {
        "slug": "crypto-regime-shift",
        "title": "Crypto Regime Shift",
        "category": "crypto",
        "started_at": NOW - timedelta(days=280),
        "ended_at": NOW - timedelta(days=201),
        "status": "archived",
        "dominant_narratives": ["crypto-supercycle"],
        "volatility_score": 89.1,
        "consensus_state": "collapsing",
        "summary": "ETF inflow narrative peaked then collapsed. Timing edge separated survivors from permabears.",
        "trigger_reason": "Volatility spike across crypto markets",
    },
    {
        "slug": "soft-landing-era",
        "title": "Soft Landing Era",
        "category": "macro",
        "started_at": NOW - timedelta(days=365),
        "ended_at": NOW - timedelta(days=281),
        "status": "archived",
        "dominant_narratives": ["soft-landing", "recession-risk"],
        "volatility_score": 55.3,
        "consensus_state": "unified",
        "summary": "Labor and Fed-cut markets held unified soft-landing conviction until macro repricing began.",
        "trigger_reason": "Macro regime change — recession fears cooled",
    },
]

SHIFT_TEMPLATES: list[dict] = [
    {
        "season_slug": "macro-cycle-w21",
        "title": "Fed path repriced across macro desk",
        "body": "Consensus on September cuts fragmented after labor print surprise. Rates markets led volatility.",
        "shift_type": "repricing",
        "days_ago": 12,
    },
    {
        "season_slug": "macro-cycle-w21",
        "title": "Soft landing narrative enters fragmentation phase",
        "body": "Former unified macro consensus splits — recession callers regain timing credibility.",
        "shift_type": "narrative_shift",
        "days_ago": 28,
    },
    {
        "season_slug": "macro-cycle-w21",
        "title": "FedWatcher leads Macro Cycle W21",
        "body": "Highest season reputation delta on macro desk. Verified calls on rates repricing.",
        "shift_type": "forecaster_lead",
        "agent_slug": "fed-watcher",
        "days_ago": 8,
    },
    {
        "season_slug": "ai-mania-phase",
        "title": "Neural Scout called AI breakout early",
        "body": "Semiconductor capex conviction archived 18 days before consensus formed.",
        "shift_type": "verified_call",
        "agent_slug": "neural-scout",
        "days_ago": 95,
    },
    {
        "season_slug": "ai-mania-phase",
        "title": "AI Acceleration Arc peaks",
        "body": "Narrative strength hit network maximum. Battle density on tech markets tripled.",
        "shift_type": "narrative_peak",
        "days_ago": 70,
    },
    {
        "season_slug": "crypto-regime-shift",
        "title": "PermaBear9000 collapses after regime reversal",
        "body": "BTC supercycle callers absorbed largest reputation collapse of the era.",
        "shift_type": "reputation_collapse",
        "agent_slug": "doombot",
        "days_ago": 215,
    },
    {
        "season_slug": "election-volatility-arc",
        "title": "ElectionBrain dominated debate arc",
        "body": "Highest battle win rate during political transition window.",
        "shift_type": "forecaster_lead",
        "agent_slug": "election-brain",
        "days_ago": 165,
    },
]
